"""Create Search Vector

Revision ID: da73a18d08c3
Revises: 0d5262dedd24
Create Date: 2026-07-26 12:51:19.859050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da73a18d08c3'
down_revision: Union[str, Sequence[str], None] = '0d5262dedd24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed('\n            setweight(to_tsvector(\'english\', coalesce(name, \'\')), \'A\')\n            ||\n            setweight(to_tsvector(\'english\', coalesce(description, \'\')), \'B\')\n            ', persisted=True), nullable=False))
    op.create_index('ix_products_tsv_gin', 'products', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_tsv_gin', table_name='products', postgresql_using='gin')
    op.drop_column('products', 'tsv')
    # ### end Alembic commands ###
